
/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { useState, useEffect } from 'react';
import { Platform, StyleSheet, Text, TextInput, View, Button, NativeModules, Alert, Switch, ScrollView, PermissionsAndroid, DeviceEventEmitter, NativeEventEmitter } from 'react-native';
import { sha512 } from 'js-sha512';
import { ApolloClient, HttpLink, InMemoryCache, gql, ApolloLink } from '@apollo/client';
import { Observable } from '@apollo/client/utilities';
const { PayUBizSdk } = NativeModules;

// Custom logging link to log all requests
const loggingLink = new ApolloLink((operation, forward) => {
    console.log('========== APOLLO CLIENT REQUEST ==========');
    console.log('Operation Name:', operation.operationName);
    console.log('Query:', operation.query.loc?.source.body);
    console.log('Variables:', JSON.stringify(operation.variables, null, 2));
    console.log('=========================================');
    return forward(operation);
});

// Custom Link to format GraphQL request as string (matching Postman format)
// The PHP endpoint expects the GraphQL query as a STRING in the request body
const customGraphQLLink = new ApolloLink((operation, forward) => {
    // Intercept the generatePaymentHash mutation and format it correctly
    if (operation.operationName === 'generatePaymentHash') {
        const { key } = operation.variables;
        const url = "https://createpayuhashphp.onrender.com/createPayuHashKey.php";
        
        console.log('========== CUSTOM GRAPHQL REQUEST ==========');
        console.log('URL:', url);
        console.log('Hash String:', key);
        
        // Format the GraphQL query as a string (matching Postman format)
        // The hash string should be plain text - only escape quotes for GraphQL string literal
        // Don't escape backslashes as they might be part of the JSON structure
        const escapedKey = key.replace(/"/g, '\\"');
        const graphQLQueryString = `mutation { createPayuHashKey ( hashname: "${escapedKey}") { get_payment_hash }}`;
        
        console.log('========== PAYLOAD DETAILS ==========');
        console.log('Original Hash String:', key);
        console.log('Escaped Hash String:', escapedKey);
        console.log('GraphQL Query String:', graphQLQueryString);
        
        const requestBody = {
            query: graphQLQueryString,
            variables: {}
        };
        
        console.log('Request Body (JSON):', JSON.stringify(requestBody, null, 2));
        console.log('Request Body (raw string):', JSON.stringify(requestBody));
        console.log('=====================================');
        
        const requestPromise = fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(requestBody)
        })
        .then(response => {
            console.log('========== SERVER RESPONSE ==========');
            console.log('Status:', response.status);
            console.log('Status Text:', response.statusText);
            console.log('OK:', response.ok);
            
            if (!response.ok) {
                return response.text().then(text => {
                    console.error('Error Response Body:', text);
                    throw new Error(`Server error: ${response.status} ${response.statusText} - ${text}`);
                });
            }
            
            return response.json().then(data => {
                console.log('Response Data:', JSON.stringify(data, null, 2));
                
                // Return the response in Apollo Client format
                return {
                    data: data.data || {
                        createPayuHashKey: {
                            get_payment_hash: data?.get_payment_hash || data?.data?.get_payment_hash
                        }
                    }
                };
            });
        })
        .catch(error => {
            console.error('========== REQUEST ERROR ==========');
            console.error('Error:', error);
            throw error;
        });
        
        // Convert Promise to Observable using ApolloLink's pattern
        // ApolloLink expects an Observable, so we create one manually
        return new Observable(observer => {
            requestPromise
                .then(result => {
                    observer.next(result);
                    observer.complete();
                })
                .catch(error => {
                    observer.error(error);
                });
        });
    }
    
    // For other operations, use the default HTTP link
    return forward(operation);
});

// HTTP Link (fallback for other operations)
const httpLink = new HttpLink({ 
    uri: "https://createpayuhashphp.onrender.com/createPayuHashKey.php"
});

// Initialize Apollo Client OUTSIDE component with logging
const client = new ApolloClient({
    link: ApolloLink.from([loggingLink, customGraphQLLink, httpLink]),
    cache: new InMemoryCache(),
});

// GraphQL Mutation OUTSIDE component
const GENERATE_PAYMENT_HASH = gql`
    mutation generatePaymentHash($key: String!) {
        createPayuHashKey(hashname: $key) {
            get_payment_hash
        }
    }
`;

// Event Queue System for Hash Generation
const eventQueue = [];
let processing = false;

// Function to process hash generation requests
async function processNextEvent() {
    console.log('========== processNextEvent CALLED ==========');
    console.log('Current processing status:', processing);
    console.log('Queue length:', eventQueue.length);
    
    if (processing || eventQueue.length === 0) {
        console.log('⏸️ Skipping - Processing:', processing, '| Queue empty:', eventQueue.length === 0);
        return;
    }

    processing = true;
    console.log('✅ Starting to process next event');
    
    const event = eventQueue.shift();
    console.log('📦 Event removed from queue');
    console.log('Event details:', JSON.stringify(event, null, 2));
    console.log('Remaining queue length:', eventQueue.length);
    
    const { requestId, ...hashData } = event;
    console.log('Request ID:', requestId);
    console.log('Hash Name:', event.hashName);
    console.log('Hash String:', event.hashString);

    try {
        console.log('🔄 Calling sendBackHash...');
        const response = await sendBackHash(event.hashName, event.hashString);
        console.log('✅ sendBackHash completed successfully');
        console.log('Response:', response);
        // NativeModules.PayUBizSdk.onHashGenerated(requestId, response.hash);
    } catch (err) {
        console.error('❌ Error in processNextEvent');
        console.error('Error:', err);
        console.error('Error message:', err.message);
        // NativeModules.PayUBizSdk.onHashError(requestId, err.message);
    } finally {
        processing = false;
        console.log('🏁 Processing complete. Setting processing flag to false');
        console.log('Checking for more events in queue...');
        processNextEvent();
    }
    console.log('========== processNextEvent END ==========');
}

export default App= () => {

    const [key, setKey] = useState('smsplus');
    const [amount, setAmount] = useState("1");
    const [productInfo, setProductInfo] = useState('productInfo');
    const [firstName, setFirstName] = useState('firstName');
    const [email, setEmail] = useState('test@gmail.com');
    const [phone, setPhone] = useState('9999999999');
    const [ios_surl, setIosSurl] = useState('https://cbjs.payu.in/sdk/success');
    const [ios_furl, setIosFurl] = useState('https://cbjs.payu.in/sdk/failure');

    const [environment, setEnvironment] = useState(1 + "");
    const [android_surl, setAndroidSurl] = useState('https://cbjs.payu.in/sdk/success');
    const [android_furl, setAndroidFurl] = useState('https://cbjs.payu.in/sdk/failure');
    const [udf1, setUdf1] = useState('udf1');
    const [udf2, setUdf2] = useState('udf2');
    const [udf3, setUdf3] = useState('udf3');
    const [udf4, setUdf4] = useState('udf4');
    const [udf5, setUdf5] = useState('udf5');
    const [merchantSalt, setMerchantSalt] = useState('izF09TlpX4ZOwmf9MvXijwYsBPUmxYHD');

    const [userCredential, setUserCredential] = useState('umang:arya');

    const [enableSI, setEnableSI] = useState(false);
    const [primaryColor, setPrimaryColor] = useState('#aabbcc');
    const [secondaryColor, setSecondaryColor] = useState('#000000');
    const [merchantName, setMerchantName] = useState("Rashan vala");
    const [merchantLogo, setMerchantLogo] = useState("Jio");
    const [showExitConfirmationOnCheckoutScreen, setShowExitConfirmationOnCheckoutScreen] = useState(true);
    const [showExitConfirmationOnPaymentScreen, setShowExitConfirmationOnPaymentScreen] = useState(true);

    const [cartDetails, setCartDetails] = useState([{ 'Order': 'Value' }, { 'Key Name': 'Value1' }]);
    const [paymentModesOrder, setPaymentModesOrder] = useState([{ 'UPI': 'TEZ' }, { 'Wallets': 'PAYTM' }, { 'EMI': '' },{'Wallets': 'PHONEPE'}]);
    const [surePayCount, setSurePayCount] = useState(1);
    const [merchantResponseTimeout, setMerchantResponseTimeout] = useState(10000);
    //const [showExitConfirmationOnPaymentScreen, setShowExitConfirmationOnPaymentScreen] = useState(true);
    const [autoSelectOtp, setAutoSelectOtp] = useState(true);
    const [enforcePaymentEnable, setEnforcePaymentEnable] = useState(false);
    const [showCbToolbar, setShowCbToolbar] = useState(true);
    const [autoApprove, setAutoApprove] = useState(false);
    const [merchantSMSPermission, setMerchantSMSPermission] = useState(false);
    const [showAlert, setShowAlert] = useState(false);

    displayAlert = (title, value) => {
         if (showAlert == false) {
             console.log('displayAlert ' + title + ' ' + value);
             setShowAlert(true);
             Alert.alert(title, value);
             //setState({ showAlert: true }, () => Alert.alert(title, value));
 
         }
         setShowAlert(false);
     }
     toggleAutoApproveOTP = (value) => {
 
         //setState({ autoApprove: value })
         setAutoApprove(value);
     }
 
     toggleEnableSI = (value) => {
         setEnableSI(value);
         //setState({ enableSI: value })
     }
 
     toggleSelectOTP = (value) => {
         setAutoSelectOtp(value);
         //setState({ autoSelectOtp: value })
     }
     toggleEnforcePaymentEnable = (value) => {
        setEnforcePaymentEnable(value);
        //setState({ autoSelectOtp: value })
    }
     toggleViewPort = (value) => {
 
         //setState({ viewPortWideEnable: value })
     }
     togglePermission = (value) => {
         setMerchantSMSPermission(value);
         requestSMSPermission()
         //setState({ merchantSMSPermission: value })
 
     }
 
     requestSMSPermission = async () => {
         try {
             const granted = await PermissionsAndroid.request(
                 PermissionsAndroid.PERMISSIONS.RECEIVE_SMS,
                 {
                     title: "Sample App SMS Permission",
                     message:
                         "Sample App needs access to your sms to autofill OTP on Bank Pages ",
                     buttonNeutral: "Ask Me Later",
                     buttonNegative: "Cancel",
                     buttonPositive: "OK"
                 }
             );
             if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                 console.log("SMS Permission Granted!");
             } else {
                 console.log("SMS Permission Denied");
             }
         } catch (err) {
             console.warn(err);
         }
     };
 
     //Register eventEmitters here
     useEffect(() => {
         const eventEmitter = new NativeEventEmitter(PayUBizSdk);
 
         payUOnPaymentSuccess = eventEmitter.addListener('onPaymentSuccess', onPaymentSuccess);
         payUOnPaymentFailure = eventEmitter.addListener('onPaymentFailure', onPaymentFailure);
         payUOnPaymentCancel = eventEmitter.addListener('onPaymentCancel', onPaymentCancel);
         payUOnError = eventEmitter.addListener('onError', onError);
         payUGenerateHash = eventEmitter.addListener('generateHash', generateHash);
    //Unregister eventEmitters here
         return () => {
            console.log("Unsubscribed!!!!")
            payUOnPaymentSuccess.remove();
            payUOnPaymentFailure.remove();
            payUOnPaymentCancel.remove();
            payUOnError.remove();
            payUGenerateHash.remove();
       }

     }, [merchantSalt])
 
     onPaymentSuccess = (e) => {
         console.log(e.merchantResponse);
         console.log(e.payuResponse);
         displayAlert('onPaymentSuccess', JSON.stringify(e));
     }
     onPaymentFailure = (e) => {
         console.log(e);
         console.log(e.merchantResponse);
         console.log(e.payuResponse);
         displayAlert('onPaymentFailure', JSON.stringify(e));
     }
     onPaymentCancel = (e) => {
         console.log('onPaymentCancel isTxnInitiated -' + e);
         displayAlert('onPaymentCancel', JSON.stringify(e));
     }
     onError = (e) => {
         console.log(e);
         displayAlert('onError', JSON.stringify(e));
     }
     generateHash = (e) => {
         console.log('========== generateHash TRIGGERED ==========');
         console.log('Hash Name:', e.hashName);
         console.log('Hash String:', e.hashString);
         console.log('Request ID:', e.requestId);
         console.log('Current queue length BEFORE push:', eventQueue.length);
        
        // Push event to queue with all ånecessary data
        const eventData = {
            requestId: e.requestId,
            hashName: e.hashName,
            hashString: e.hashString
        };
        
        console.log('📥 Pushing event to queue:', JSON.stringify(eventData, null, 2));
        eventQueue.push(eventData);
        console.log('Queue length AFTER push:', eventQueue.length);
        console.log('Full queue state:', JSON.stringify(eventQueue, null, 2));

        // Process the next event in queue
        console.log('🚀 Calling processNextEvent...');
        processNextEvent();
        console.log('========== generateHash END ==========');
     }
     createPaymentParams = () => {
         var txnid = new Date().getTime().toString();
         console.log('AutoSelectOtp: '+autoSelectOtp +'MerchantSmsPermission: '+merchantSMSPermission);
         var payUPaymentParams = {
             key: key,
             transactionId: txnid,
             amount: amount,
             productInfo: productInfo,
             firstName: firstName,
             email: email,
             phone: phone,
             ios_surl: ios_surl,
             ios_furl: ios_furl,
             android_surl: android_surl,
             android_furl: android_furl,
             environment: environment,
             userCredential: userCredential,
             additionalParam: {
                 udf1: udf1,
                 udf2: udf2,
                 udf3: udf3,
                 udf4: udf4,
                 udf5: udf5, 
                 walletUrn:'100000'
             }
         }
         var siParamObject = {
             isFreeTrial: true,
             billingAmount: '10',
             billingInterval: '1',
             paymentStartDate: '2024-05-20',
             paymentEndDate: '2025-04-30',
             billingCycle: 'DAILY', //Can be any of 'daily','weekly','yearly','adhoc','once','monthly'
             remarks: 'Test SI transcaction',
             billingCurrency: 'INR'
         }
         if (enableSI) {
             console.log('Inside enableSI')
             payUPaymentParams.payUSIParams = siParamObject
         }
 
         var payUCheckoutProConfig = {
             primaryColor: primaryColor,
             secondaryColor: secondaryColor,
             merchantName: merchantName,
             merchantLogo: merchantLogo,
             showExitConfirmationOnCheckoutScreen: showExitConfirmationOnCheckoutScreen,
             showExitConfirmationOnPaymentScreen: showExitConfirmationOnPaymentScreen,
             cartDetails: cartDetails,
             paymentModesOrder: paymentModesOrder,
             surePayCount: surePayCount,
            //  enableRE:true,
             merchantResponseTimeout: merchantResponseTimeout,
             autoSelectOtp: autoSelectOtp,
             // Android specific property
             autoApprove: autoApprove,
             merchantSMSPermission: merchantSMSPermission,
             showCbToolbar: showCbToolbar,
         }
         if (enforcePaymentEnable) {
            payUCheckoutProConfig["enforcePaymentList"] = [{'payment_type' :"NB"}, {'payment_type' :"CARD"}];
         }
        
         return {
             payUPaymentParams: payUPaymentParams,
             payUCheckoutProConfig: payUCheckoutProConfig
         };
     }
   //Used to send back hash generated to SDK - Server side only (using Postman format)
   //Used to send back hash generated to SDK - Server side only (using Postman format)
  sendBackHash = async (hashName, hashString) => {
      const startTime = Date.now();
      console.log('========== sendBackHash START ==========');
      console.log('⏰ Timestamp:', new Date().toISOString());
      console.log('Hash Name:', hashName);
      console.log('Hash String:', hashString);

      try {
 
          console.log('========== REQUEST PAYLOAD ==========');
          console.log('URL:', 'https://createpayuhashphp.onrender.com/createPayuHashKey.php');
          console.log('Hash String for mutation:', hashString);
          console.log('====================================================');
          console.log('📤 Sending GraphQL mutation...');

          // Use Apollo Client's mutate method with proper GraphQL format
          const response = await client.mutate({
              mutation: GENERATE_PAYMENT_HASH,
              variables: {
                  key: hashString
              },
              fetchPolicy: 'no-cache'
          });

          const requestDuration = Date.now() - startTime;
          console.log('========== RESPONSE RECEIVED ==========');
          console.log('⏱️ Request duration:', requestDuration + 'ms');
          console.log('Response:', JSON.stringify(response, null, 2));
       
          if (!response || !response.data) {
              throw new Error('No data received from server');
          }
       
          // Extract hash value from response
          var hashValue = response?.data?.createPayuHashKey?.get_payment_hash;

          console.log('🔑 Hash generated on server side ===>>>', hashValue);
          if(hashName == "get_checkout_details"){
             hashValue = calculateHash(hashString);
          }

          if (hashValue) {
              var result = { [hashName]: hashValue };
              console.log('📨 Sending result to PayU SDK:', result);
              PayUBizSdk.hashGenerated(result);
              console.log('✅ Hash sent successfully to PayU SDK');
              console.log('========== sendBackHash END (SUCCESS) ==========');
              console.log('⏱️ Total execution time:', (Date.now() - startTime) + 'ms');
              return { success: true, hash: hashValue };
          } else {
              console.error('⚠️ No hash value received from server');
              console.error('Response structure:', JSON.stringify(response, null, 2));
              console.error('Payment cannot proceed without server hash');
              throw new Error('No hash value in response');
          }
      } catch (error: any) {
          const errorDuration = Date.now() - startTime;
          console.error('========== ERROR in sendBackHash ==========');
          console.error('⏱️ Failed after:', errorDuration + 'ms');
          console.error('Error Type:', typeof error);
          console.error('Error:', error);
          console.error('Error Message:', error?.message);
          
          // Log Apollo Client specific error details
          if (error?.networkError) {
              console.error('========== NETWORK ERROR DETAILS ==========');
              console.error('Network Error Object:', JSON.stringify(error.networkError, null, 2));
              if (error.networkError?.statusCode) {
                  console.error('Status Code:', error.networkError.statusCode);
              }
              if (error.networkError?.result) {
                  console.error('Server Result:', JSON.stringify(error.networkError.result, null, 2));
              }
              if (error.networkError?.bodyText) {
                  console.error('Response Body Text:', error.networkError.bodyText);
              }
              if (error.networkError?.response) {
                  console.error('Response Object:', JSON.stringify(error.networkError.response, null, 2));
              }
              console.error('===========================================');
          }
          
          if (error?.graphQLErrors && error.graphQLErrors.length > 0) {
              console.error('GraphQL Errors:', JSON.stringify(error.graphQLErrors, null, 2));
          }
          
          console.error('Error Stack:', error?.stack);
          console.error('Payment cannot proceed due to server error');
          console.error('========== ERROR END ==========');
          throw error;
      }
   }
    
    calculateHash = (data) => {
        console.log(data);
        var result = sha512(data+merchantSalt);
        console.log(result);
        return result;
    }
     launchPayU = () => {
         console.log('Method launched amount =' + JSON.stringify(createPaymentParams()));
         PayUBizSdk.openCheckoutScreen(createPaymentParams());
     }
     return (
         <ScrollView style={styles.container}>
             <View >
             <Text style={styles.welcome}>☆ PayUCheckoutPro ☆{'\n'}Sample App</Text> 
             </View> 
             <View style={styles.cell}>
                 <Text style={styles.category}>Merchant Key</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={key} onChangeText={text => { setKey(text)}} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Merchant Salt</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={merchantSalt} onChangeText={text => { setMerchantSalt(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Environment</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={environment} onChangeText={text => { setEnvironment(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Enter Transcation{'\n'}Amount</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={amount} onChangeText={text => { setAmount(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Email</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={email} onChangeText={text => { setEmail(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>User Credential</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={userCredential} onChangeText={text => { setUserCredential(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>UDF1</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={udf1} onChangeText={text => { setUdf1(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>UDF2</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={udf2} onChangeText={text => { setUdf2(text)}} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>UDF3</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={udf3} onChangeText={text => { setUdf3(text)}} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>UDF4</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={udf4} onChangeText={text => { setUdf4(text)}} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>UDF5</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={udf5} onChangeText={text => { setUdf5(text) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Merchant Surl/Furl{'\n'}Timeout</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={String(merchantResponseTimeout)} onChangeText={text => { setMerchantResponseTimeout( parseInt(text)) }} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Auto Select Otp</Text>
                 <Switch style={styles.valuesSwitch} value={autoSelectOtp} onValueChange={toggleSelectOTP} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Enable enforce{'\n'}Payment</Text>
                 <Switch style={styles.valuesSwitch} value={enforcePaymentEnable} onValueChange={toggleEnforcePaymentEnable} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>SMS Permission</Text>
                 <Switch style={styles.valuesSwitch} value={merchantSMSPermission} onValueChange={togglePermission} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Auto Approve Otp</Text>
                 <Switch style={styles.valuesSwitch} value={autoApprove} onValueChange={toggleAutoApproveOTP} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Enable SI</Text>
                 <Switch style={styles.valuesSwitch} value={enableSI} onValueChange={toggleEnableSI} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>SurePay (0-3)</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={String(surePayCount)} onChangeText={text => { setSurePayCount(parseInt(text) )}} />
             </View>
             <View style={styles.cell}>
                 <Text style={styles.category}>Merchant Name</Text>
                 <TextInput style={styles.valuesTextInput} defaultValue={merchantName} onChangeText={text => { setMerchantName(text) }} />
             </View>
             <Button title={'Pay Now'}  onPress={()=>{launchPayU()}} />
         </ScrollView>
     );
 }


 const styles = StyleSheet.create({
     contentContainerStyle: {
         flex: 2,
         justifyContent: 'center',
         alignItems: 'center',
         backgroundColor: '#F5FCFF',
 
     },
     welcome: {
         fontSize: 20,
         textAlign: 'center',
         margin: 10,
         marginTop: 50,
         marginBottom: 20,
         padding:10,
         backgroundColor: '#6495DD',
         fontWeight:"bold"  
     },
     category: {
         fontSize: 14,
         textAlign: 'left',
         fontWeight: "bold"
     },
     values: {
         fontSize: 14,
         textAlign: 'right'
     },
     valuesTextInput: {
        fontSize: 14,
        textAlign: 'right',
        width:180,
        borderWidth: .5,
        borderRadius: 5,
        padding: 10,
        backgroundColor:'#F2F3F4'
    },
     valuesSwitch: {
        fontSize: 14,
        textAlign: 'right'
    },
     instructions: {
         textAlign: 'center',
         color: '#333333',
         marginBottom: 5,
     },
     cell: {
         flex: 1,
         flexDirection: 'row',
         justifyContent: 'space-between',
         alignItems: 'center',
         margin: 10,
     },
 });
 

